### ISSUE TITLE
Looking for maintainer

### ISSUE THREAD

**Issue by bschmitt** [bschmitt/laravel-amqp#41]
As my time is limited recently and I guess this package is quite helpful for others, I want to ask if there is someone which can help me or take over the ownership?

**Comment by stevenklar** [comment]
Thank you for this project. I could help working on some issues and doing pull requests as an additional maintaner. Taking over the ownership doesn't feels for me as I don't have a vision for this package.

**Comment by stevenklar** [comment]
@bschmitt What do you think? Would you give me rights to merge PR and make releases?

**Comment by stevenklar** [comment]
Allright. I will maintain the fork for now.

**Comment by bschmitt** [comment]
@stevenklar are you now able to maintain the repository? The only thank I can do is to add you as collaborator, I have the feeling that doing more advanced stuff is tight to a github pro plan. Thank you very much! In case that doesn't work out, I'm fine moving it to your account.

**Comment by stevenklar** [comment]
As far as I concerned everything should work. Is this repository configured to automagicaly publish releases/tags to packagist, because that might be import for some users?

Push and working on Pull Requests also seems to work.

If anything is missing I will let you know. Please let me know if anything goes in a wrong direction or you don't like.

**Comment by bschmitt** [comment]
Yes, that's the case. Vielen Dank!
